In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib

In [5]:
%cd C:/Users/Peter/Downloads
%ls

C:\Users\Peter\Downloads
 Volume in drive C has no label.
 Volume Serial Number is C41F-BCB2

 Directory of C:\Users\Peter\Downloads

12/01/2017  08:37 AM    <DIR>          .
12/01/2017  08:37 AM    <DIR>          ..
08/30/2017  01:32 PM    <DIR>          Books, Notes and various PDFs
11/13/2017  08:08 PM         2,155,859 census.csv
12/01/2017  08:37 AM             8,652 coindesk-bpi-USD-close_data-2016-12-01_2017-12-01.csv
12/01/2017  08:35 AM            53,782 coindesk-bpi-USD-close_data-2017-11-30_2017-12-01.csv
11/10/2017  04:27 PM            15,004 CURRICULUM VITAE current.docx
11/10/2017  04:20 PM            37,376 CV.doc
10/31/2017  09:05 AM    <DIR>          datasets
10/31/2017  08:47 AM         4,005,545 fifa-18-demo-player-dataset.zip
11/22/2017  09:21 AM        84,130,264 GitHubDesktopSetup.exe
02/20/2017  10:25 AM    <DIR>          HP Downloads
11/30/2017  09:21 AM             4,210 Kisumu_County_Monthly_Food_Security_Statistics.csv
11/30/2017  09:46 AM             4,275 Kisumu_Food_Stats.csv
11/29/2017  07:49 PM               285 Laikipia_Pop_Pyramid_Age_Groups2009.csv
11/16/2017  06:16 PM        21,690,402 Mining-the-Social-Web-2nd-Edition.pdf
10/05/2017  05:09 PM           543,627 MUSHROOM-BEEF-STEW-.pdf
11/12/2017  03:03 PM             8,419 olympics.csv
11/22/2017  09:35 AM    <DIR>          pandas_tutorial-master
11/22/2017  09:24 AM         2,416,093 pandas_tutorial-master.zip
11/13/2017  09:19 PM           229,944 Patreon-Case-Study.pdf
10/05/2017  05:12 PM           822,700 PLUM-MARINATED-SPICY-PORK.pdf
11/12/2017  09:49 AM             2,079 Revenue_Projections_for_Kisumu_County_FY_20152016.csv
11/22/2017  09:26 AM    <DIR>          scipy-2017-tutorial-pandas-master
08/30/2017  01:35 PM    <DIR>          software applications
10/31/2017  10:21 AM            88,318 SS JAPAN LTD_EDITED (1).pdf
10/31/2017  07:47 AM            87,035 SS JAPAN LTD_EDITED.pdf
10/19/2017  07:42 AM           321,527 tutorials_python.zip
11/21/2017  08:01 AM             9,039 tweet_activity_metrics_psonyango_20171025_20171122_en.csv
10/05/2017  05:15 PM           457,600 UKWAJU-MARINATED-CHICKEN-THIGHS.pdf
11/01/2017  09:05 AM           515,120 video-game-sales-with-ratings.zip
              23 File(s)    117,607,155 bytes
               8 Dir(s)  225,894,793,216 bytes free

In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series
import matplotlib.pyplot as plt

In [7]:
bitcoins = pd.read_csv('coindesk-bpi-USD-close_data-2016-12-01_2017-12-01.csv')

In [8]:
bitcoins.set_index('Date',inplace=True)

In [9]:
bitcoins

                 Close Price
Date
12/1/2016 0:00        753.25
12/2/2016 0:00        771.41
12/3/2016 0:00        764.97
12/4/2016 0:00        766.46
12/5/2016 0:00        750.71
12/6/2016 0:00        758.81
12/7/2016 0:00        763.90
12/8/2016 0:00        766.75
12/9/2016 0:00        770.41
12/10/2016 0:00       773.21
12/11/2016 0:00       768.62
12/12/2016 0:00       777.91
12/13/2016 0:00       775.25
12/14/2016 0:00       776.64
12/15/2016 0:00       775.48
12/16/2016 0:00       780.85
12/17/2016 0:00       788.58
12/18/2016 0:00       788.59
12/19/2016 0:00       790.16
12/20/2016 0:00       798.78
12/21/2016 0:00       833.10
12/22/2016 0:00       858.74
12/23/2016 0:00       916.79
12/24/2016 0:00       894.20
12/25/2016 0:00       894.48
12/26/2016 0:00       902.55
12/27/2016 0:00       931.11
12/28/2016 0:00       978.01
12/29/2016 0:00       969.62
12/30/2016 0:00       960.47
...                      ...
11/2/2017 0:00       7030.00
11/3/2017 0:00       7161.45
11/4/2017 0:00       7387.00
11/5/2017 0:00       7382.45
11/6/2017 0:00       6958.21
11/7/2017 0:00       7118.80
11/8/2017 0:00       7458.79
11/9/2017 0:00       7146.78
11/10/2017 0:00      6570.31
11/11/2017 0:00      6337.00
11/12/2017 0:00      5857.32
11/13/2017 0:00      6517.68
11/14/2017 0:00      6598.77
11/15/2017 0:00      7279.00
11/16/2017 0:00      7843.94
11/17/2017 0:00      7689.91
11/18/2017 0:00      7776.94
11/19/2017 0:00      8033.94
11/20/2017 0:00      8238.20
11/21/2017 0:00      8095.59
11/22/2017 0:00      8230.69
11/23/2017 0:00      8002.64
11/24/2017 0:00      8201.46
11/25/2017 0:00      8763.78
11/26/2017 0:00      9326.59
11/27/2017 0:00      9739.05
11/28/2017 0:00      9908.23
11/29/2017 0:00      9816.35
11/30/2017 0:00      9916.54
12/1/2017 5:35       9666.98

[366 rows x 1 columns]

In [17]:
bitcoins.plot(style = 'g--')

In [18]:
import os
os.getcwd()

'C:\\Users\\Peter\\Downloads'